/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bmi;

import javax.swing.JOptionPane;

/**
 *
 * @author sanda
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        heightCm.setVisible(true);
        heightInch.setVisible(false);
        heightFt.setVisible(false);
        feetLbl.setVisible(false);
        
        suggesPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        genderLbl = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        ageLbl = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        heightLbl = new javax.swing.JLabel();
        heightPanel = new javax.swing.JPanel();
        heightInch = new javax.swing.JTextField();
        heightFt = new javax.swing.JTextField();
        feetLbl = new javax.swing.JLabel();
        heightCm = new javax.swing.JTextField();
        heightType = new javax.swing.JComboBox<>();
        weightLbl = new javax.swing.JLabel();
        weight = new javax.swing.JTextField();
        weightType = new javax.swing.JComboBox<>();
        calBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        resultPanel = new javax.swing.JPanel();
        hLbl = new javax.swing.JLabel();
        h = new javax.swing.JLabel();
        hUnit = new javax.swing.JLabel();
        wLbl = new javax.swing.JLabel();
        w = new javax.swing.JLabel();
        wUnit = new javax.swing.JLabel();
        bmiLbl = new javax.swing.JLabel();
        bmi = new javax.swing.JLabel();
        statusLbl = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        aLbl = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        heightLbl2 = new javax.swing.JLabel();
        suggesPanel = new javax.swing.JPanel();
        maxW = new javax.swing.JLabel();
        unit = new javax.swing.JLabel();
        minW = new javax.swing.JLabel();
        unit1 = new javax.swing.JLabel();
        footerLbl = new javax.swing.JLabel();
        dash = new javax.swing.JLabel();
        heightLbl1 = new javax.swing.JLabel();
        info = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(13, 20, 40));

        heading.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        heading.setForeground(new java.awt.Color(255, 255, 255));
        heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heading.setText("Body Mass Index");

        genderLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderLbl.setForeground(new java.awt.Color(255, 255, 255));
        genderLbl.setText("Gender : ");

        male.setBackground(new java.awt.Color(13, 20, 40));
        male.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        male.setForeground(new java.awt.Color(142, 68, 173));
        male.setSelected(true);
        male.setText("Male");
        male.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        female.setBackground(new java.awt.Color(13, 20, 40));
        female.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("Female");
        female.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });

        ageLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ageLbl.setForeground(new java.awt.Color(255, 255, 255));
        ageLbl.setText("Age : ");

        age.setBackground(new java.awt.Color(13, 20, 40));
        age.setForeground(new java.awt.Color(255, 255, 255));
        age.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 68, 173)));
        age.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ageMouseClicked(evt);
            }
        });

        heightLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        heightLbl.setForeground(new java.awt.Color(255, 255, 255));
        heightLbl.setText("Height : ");

        heightPanel.setBackground(new java.awt.Color(13, 20, 40));
        heightPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        heightInch.setBackground(new java.awt.Color(13, 20, 40));
        heightInch.setForeground(new java.awt.Color(255, 255, 255));
        heightInch.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        heightInch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 68, 173)));
        heightInch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                heightInchMouseClicked(evt);
            }
        });
        heightPanel.add(heightInch, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 40, 20));

        heightFt.setBackground(new java.awt.Color(13, 20, 40));
        heightFt.setForeground(new java.awt.Color(255, 255, 255));
        heightFt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        heightFt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 68, 173)));
        heightFt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                heightFtMouseClicked(evt);
            }
        });
        heightPanel.add(heightFt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 20));

        feetLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        feetLbl.setForeground(new java.awt.Color(255, 255, 255));
        feetLbl.setText("Feet");
        heightPanel.add(feetLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        heightCm.setBackground(new java.awt.Color(13, 20, 40));
        heightCm.setForeground(new java.awt.Color(255, 255, 255));
        heightCm.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        heightCm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 68, 173)));
        heightCm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                heightCmMouseClicked(evt);
            }
        });
        heightPanel.add(heightCm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 125, 20));

        heightType.setBackground(new java.awt.Color(13, 20, 40));
        heightType.setForeground(new java.awt.Color(255, 255, 255));
        heightType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cm", "inch" }));
        heightType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 68, 173)));
        heightType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        heightType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightTypeActionPerformed(evt);
            }
        });

        weightLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        weightLbl.setForeground(new java.awt.Color(255, 255, 255));
        weightLbl.setText("Weight : ");

        weight.setBackground(new java.awt.Color(13, 20, 40));
        weight.setForeground(new java.awt.Color(255, 255, 255));
        weight.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        weight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 68, 173)));
        weight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                weightMouseClicked(evt);
            }
        });

        weightType.setBackground(new java.awt.Color(13, 20, 40));
        weightType.setForeground(new java.awt.Color(255, 255, 255));
        weightType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kg", "pound" }));
        weightType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 68, 173)));
        weightType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        calBtn.setBackground(new java.awt.Color(142, 68, 173));
        calBtn.setForeground(new java.awt.Color(255, 255, 255));
        calBtn.setText("Calculate");
        calBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        calBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                calBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                calBtnMouseExited(evt);
            }
        });
        calBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calBtnActionPerformed(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(142, 68, 173));
        clearBtn.setForeground(new java.awt.Color(255, 255, 255));
        clearBtn.setText("Clear");
        clearBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        clearBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearBtnMouseExited(evt);
            }
        });
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        resultPanel.setBackground(new java.awt.Color(13, 20, 40));
        resultPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Result", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(142, 68, 173))); // NOI18N

        hLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hLbl.setForeground(new java.awt.Color(255, 255, 255));
        hLbl.setText("Height        : ");

        h.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        h.setForeground(new java.awt.Color(142, 68, 173));
        h.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        hUnit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hUnit.setForeground(new java.awt.Color(255, 255, 255));
        hUnit.setText("M");

        wLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        wLbl.setForeground(new java.awt.Color(255, 255, 255));
        wLbl.setText("Weight       : ");

        w.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        w.setForeground(new java.awt.Color(142, 68, 173));
        w.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        wUnit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        wUnit.setForeground(new java.awt.Color(255, 255, 255));
        wUnit.setText("KG");

        bmiLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bmiLbl.setForeground(new java.awt.Color(255, 255, 255));
        bmiLbl.setText("BMI Value  : ");

        bmi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bmi.setForeground(new java.awt.Color(142, 68, 173));
        bmi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        statusLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        statusLbl.setForeground(new java.awt.Color(255, 255, 255));
        statusLbl.setText("Status        : ");

        status.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        status.setForeground(new java.awt.Color(255, 255, 255));
        status.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        aLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        aLbl.setForeground(new java.awt.Color(255, 255, 255));
        aLbl.setText("Age             : ");

        a.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        a.setForeground(new java.awt.Color(142, 68, 173));
        a.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        heightLbl2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        heightLbl2.setForeground(new java.awt.Color(255, 255, 255));
        heightLbl2.setText("years");

        javax.swing.GroupLayout resultPanelLayout = new javax.swing.GroupLayout(resultPanel);
        resultPanel.setLayout(resultPanelLayout);
        resultPanelLayout.setHorizontalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(resultPanelLayout.createSequentialGroup()
                        .addComponent(aLbl)
                        .addGap(18, 18, 18)
                        .addComponent(a, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(heightLbl2))
                    .addGroup(resultPanelLayout.createSequentialGroup()
                        .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusLbl)
                            .addComponent(bmiLbl)
                            .addComponent(hLbl)
                            .addComponent(wLbl))
                        .addGap(18, 18, 18)
                        .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(resultPanelLayout.createSequentialGroup()
                                    .addGap(26, 26, 26)
                                    .addComponent(bmi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(resultPanelLayout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(w, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(wUnit)))
                            .addGroup(resultPanelLayout.createSequentialGroup()
                                .addComponent(h, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hUnit)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        resultPanelLayout.setVerticalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultPanelLayout.createSequentialGroup()
                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resultPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(resultPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(heightLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(h, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(w, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bmiLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bmi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        suggesPanel.setBackground(new java.awt.Color(13, 20, 40));
        suggesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        maxW.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        maxW.setForeground(new java.awt.Color(142, 68, 173));
        maxW.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        suggesPanel.add(maxW, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 60, 20));

        unit.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        unit.setForeground(new java.awt.Color(255, 255, 255));
        unit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        unit.setText("kg");
        suggesPanel.add(unit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, 20));

        minW.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        minW.setForeground(new java.awt.Color(142, 68, 173));
        minW.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        suggesPanel.add(minW, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 60, 20));

        unit1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        unit1.setForeground(new java.awt.Color(255, 255, 255));
        unit1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        unit1.setText("kg");
        suggesPanel.add(unit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, 20));

        footerLbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        footerLbl.setForeground(new java.awt.Color(255, 255, 255));
        footerLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        footerLbl.setText("Your suggested healthy weight range");
        suggesPanel.add(footerLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 286, -1));

        dash.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        dash.setForeground(new java.awt.Color(255, 255, 255));
        dash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dash.setText("-");
        suggesPanel.add(dash, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 20, 20));

        heightLbl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        heightLbl1.setForeground(new java.awt.Color(255, 255, 255));
        heightLbl1.setText("years");

        info.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        info.setForeground(new java.awt.Color(255, 255, 255));
        info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        info.setText("I");
        info.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(heading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(weightLbl)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(genderLbl)
                                .addGap(41, 41, 41)
                                .addComponent(male)
                                .addGap(36, 36, 36)
                                .addComponent(female))
                            .addComponent(resultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(heightLbl)
                                    .addComponent(ageLbl))
                                .addGap(32, 32, 32)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(heightLbl1))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(heightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(heightType, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(weightType, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(suggesPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(calBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(heading)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(male)
                            .addComponent(female))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(heightLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(heightLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(heightType, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(heightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(weightLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(weightType, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(resultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(suggesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void calculation()
    {
        Object oH = heightType.getSelectedItem();
        String typeH = oH.toString();
        
        Object oW = weightType.getSelectedItem();
        String typeW = oW.toString();
        
        float hCm = 0;
        float hM = 0;
        float hFt = 0;
        float hInch = 0;
        float w = 0;
        float bmiValue = 0;
        
        try {
            
        } catch (Exception e) {
        }
            
        if(age.getText().trim().equals("") && weight.getText().trim().equals("") && (heightCm.getText().trim().equals("") || (heightFt.getText().trim().equals("") && heightInch.getText().trim().equals("")))){
            age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
            weight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
            heightCm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
            heightFt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
            heightInch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        }
        else if(age.getText().trim().equals("")){
            age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        }
        else if(heightCm.getText().trim().equals("") && (heightFt.getText().trim().equals("") || heightInch.getText().trim().equals(""))){
            heightCm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
            heightFt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
            heightInch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        }
        else if(weight.getText().trim().equals("")){
            weight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        }
        else{
        
            this.a.setText(age.getText().trim());
            
            if(typeH.equals("cm")){
                hCm = Float.parseFloat(heightCm.getText().trim());
            }
            else if(typeH.equals("inch")){
                hFt = Float.parseFloat(heightFt.getText().trim());
                hInch = Float.parseFloat(heightInch.getText().trim());

                hCm = (float) (((hFt*12)+hInch)*2.54);
            }
            hM = (float) Math.round((hCm/100.0)*100)/100;
            this.h.setText(String.valueOf(hM));
            
            if(typeW.equals("kg")){
                w = Float.parseFloat(weight.getText().trim());
            }
            else if(typeW.equals("pound")){
                w = Float.parseFloat(weight.getText().trim());

                w = (float) (w*2.20462);
            }
            w = (float) Math.round(w*100)/100;
            this.w.setText(String.valueOf(w));

            bmiValue = (float) Math.round(w/Math.pow(hM, 2)*100)/100;
            this.bmi.setText(String.valueOf(bmiValue));
            status(bmiValue);
            
            suggesPanel.setVisible(true);
        
        }
        /*try {
            if(type == "inch"){
                hFt = Float.parseFloat(heightFt.getText().trim());
                if(heightFt.equals(null))
                    hFt = 0;
                hInch = Float.parseFloat(heightInch.getText().trim());
            }
            else if(type == "cm"){
                hCm = Float.parseFloat(heightCm.getText().trim());
            }
            w = Float.parseFloat(weight.getText().trim());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error "+e.getMessage());
        }
        
        hM = (float) (hCm/100.0);
        
        this.a.setText(age.getText().trim());
        if("inch".equals(type)){
            this.h.setText(String.valueOf(hInch));
        }
        else if("cm".equals(type)){
            this.h.setText(String.valueOf(hM));
        }*/
        
    }
    
    public void status(float bmi)
    {
        if(bmi < 18.5){
            status.setForeground(new java.awt.Color(52, 152, 219));
            status.setText("Underweight");
        }
        else if(bmi >= 18.5 && bmi <= 24.9){
            status.setForeground(new java.awt.Color(26, 188, 156));
            status.setText("Normal weight");
        }
        else if(bmi >= 25 && bmi <= 29.9){
            status.setForeground(new java.awt.Color(241, 196, 15));
            status.setText("Overweight");
        }
        else if(bmi >= 30){
            status.setForeground(new java.awt.Color(231, 76, 60));
            status.setText("Obese");
        }
    }
    
    
    private void heightTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightTypeActionPerformed
        Object o = heightType.getSelectedItem();
        String type = o.toString();
        
        switch(type){
            case "cm":
                heightCm.setVisible(true);
                heightInch.setVisible(false);
                heightFt.setVisible(false);
                feetLbl.setVisible(false);
                
                weightType.setSelectedIndex(0);
                break;
            case "inch":
                heightCm.setVisible(false);
                heightInch.setVisible(true);
                heightFt.setVisible(true);
                feetLbl.setVisible(true);
                
                weightType.setSelectedIndex(1);
                break;
        }
    }//GEN-LAST:event_heightTypeActionPerformed

    private void calBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calBtnActionPerformed
        calculation();
    }//GEN-LAST:event_calBtnActionPerformed

    private void calBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calBtnMouseEntered
        calBtn.setBackground(new java.awt.Color(255, 255, 255));
        calBtn.setForeground(new java.awt.Color(142, 68, 173));
        calBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(142, 68, 173), 2, true));
    }//GEN-LAST:event_calBtnMouseEntered

    private void calBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calBtnMouseExited
        calBtn.setBackground(new java.awt.Color(142, 68, 173));
        calBtn.setForeground(new java.awt.Color(255, 255, 255));
        calBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
    }//GEN-LAST:event_calBtnMouseExited

    private void clearBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtnMouseEntered
        clearBtn.setBackground(new java.awt.Color(255, 255, 255));
        clearBtn.setForeground(new java.awt.Color(142, 68, 173));
        clearBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(142, 68, 173), 2, true));
    }//GEN-LAST:event_clearBtnMouseEntered

    private void clearBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtnMouseExited
        clearBtn.setBackground(new java.awt.Color(142, 68, 173));
        clearBtn.setForeground(new java.awt.Color(255, 255, 255));
        clearBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
    }//GEN-LAST:event_clearBtnMouseExited

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        male.setSelected(true);
        female.setSelected(false);
        
        male.setForeground(new java.awt.Color(142, 68, 173));
        female.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        female.setSelected(true);
        male.setSelected(false);
        
        female.setForeground(new java.awt.Color(142, 68, 173));
        male.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_femaleActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        male.setSelected(true);
        maleActionPerformed(evt);
        age.setText(null);
        heightType.setSelectedIndex(0);
        heightCm.setText(null);
        heightInch.setText(null);
        heightFt.setText(null);
        weight.setText(null);
        a.setText(null);
        h.setText(null);
        w.setText(null);
        bmi.setText(null);
        status.setText(null);
        suggesPanel.setVisible(false);
    }//GEN-LAST:event_clearBtnActionPerformed

    private void ageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ageMouseClicked
        age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 68, 173)));
    }//GEN-LAST:event_ageMouseClicked

    private void heightFtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_heightFtMouseClicked
        heightFt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 68, 173)));
    }//GEN-LAST:event_heightFtMouseClicked

    private void heightInchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_heightInchMouseClicked
        heightInch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 68, 173)));
    }//GEN-LAST:event_heightInchMouseClicked

    private void heightCmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_heightCmMouseClicked
        heightCm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 68, 173)));
    }//GEN-LAST:event_heightCmMouseClicked

    private void weightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_weightMouseClicked
        weight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 68, 173)));
    }//GEN-LAST:event_weightMouseClicked

    private void infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMouseClicked
        Info i = new Info();
        i.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_infoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JLabel aLbl;
    private javax.swing.JTextField age;
    private javax.swing.JLabel ageLbl;
    private javax.swing.JLabel bmi;
    private javax.swing.JLabel bmiLbl;
    private javax.swing.JButton calBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel dash;
    private javax.swing.JLabel feetLbl;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel footerLbl;
    private javax.swing.JLabel genderLbl;
    private javax.swing.JLabel h;
    private javax.swing.JLabel hLbl;
    private javax.swing.JLabel hUnit;
    private javax.swing.JLabel heading;
    private javax.swing.JTextField heightCm;
    private javax.swing.JTextField heightFt;
    private javax.swing.JTextField heightInch;
    private javax.swing.JLabel heightLbl;
    private javax.swing.JLabel heightLbl1;
    private javax.swing.JLabel heightLbl2;
    private javax.swing.JPanel heightPanel;
    private javax.swing.JComboBox<String> heightType;
    private javax.swing.JLabel info;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton male;
    private javax.swing.JLabel maxW;
    private javax.swing.JLabel minW;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JLabel status;
    private javax.swing.JLabel statusLbl;
    private javax.swing.JPanel suggesPanel;
    private javax.swing.JLabel unit;
    private javax.swing.JLabel unit1;
    private javax.swing.JLabel w;
    private javax.swing.JLabel wLbl;
    private javax.swing.JLabel wUnit;
    private javax.swing.JTextField weight;
    private javax.swing.JLabel weightLbl;
    private javax.swing.JComboBox<String> weightType;
    // End of variables declaration//GEN-END:variables
}
